# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'iPhonoidUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for iPhonoidUI
  
end
